### ISSUE TITLE
Integrate updated theme resouces and bs4-alpha

### ISSUE THREAD

**Issue by potzenheimer** [a25kk/diako#1]
Move changes from LRA theme integration/styleguide over to local resource dir and introduce gulp build tool

**Comment by potzenheimer** [comment]
@kreativkombinat wir verwenden mal hier ein Github TIcket, um den Fortschritt zu tracken. Eventuell ist auch ein Long-running Pullrequest sinnvoll. Muss ich mir noch überlegen

**Comment by potzenheimer** [comment]
**New estimation: 4 hours.**
@kreativkombinat wir verwenden mal hier ein Github TIcket, um den Fortschritt zu tracken. Eventuell ist auch ein Long-running Pullrequest sinnvoll. Muss ich mir noch überlegen

**Comment by kreativkombinat** [comment]
Ok, einverstanden, wie lauft so ein Long-running Pullrequest ab?

**Comment by potzenheimer** [comment]
Ich habe eine branch geöffnet und werde alle changes bzgl der Umbaus dort commited. Mit Abschluss des Umbaus wird der dazugehörige Pull-Request gemerged. So behalten wir den Überblick und alle Commits sind an einer Stelle.

```bash
cd diako
git checkout issue-1-theme-update
```
Dann einfach wie gewohnt arbeiten.

**Comment by kreativkombinat** [comment]
Wo genau kann ich den git checkout machen? In theme dir? oder im buildout root?

**Comment by potzenheimer** [comment]
Nwe buildout in the works and therefore obsolete
